
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class MasterCourse extends javax.swing.JFrame {
    CollegeQuery colQ = new CollegeQuery();
    ArrayList<College> colList = colQ.collegeList();
    String selectedvalue = null;
    
    /**
     * Creates new form MasterCourse
     */
    public MasterCourse() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        fillCombo();
        
        jTable1.setShowGrid(true);
        jTable1.setGridColor(new Color(34, 167, 240));
        jTable1.setSelectionBackground(new Color(37, 116, 169));
        
        JTableHeader th = jTable1.getTableHeader();
        th.setForeground(Color.BLACK);
        th.setFont(new Font("Titillium Web", Font.TRUETYPE_FONT, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonhome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonADDCrs = new javax.swing.JButton();
        jButtonEDITCrs = new javax.swing.JButton();
        jButtonDELETECrs = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programmed by Riz Veran - BIT24");

        jPanel1.setBackground(new java.awt.Color(137, 196, 244));

        jPanel2.setBackground(new java.awt.Color(228, 120, 51));

        jButtonhome.setBackground(new java.awt.Color(242, 241, 239));
        jButtonhome.setFont(new java.awt.Font("Titillium Web", 0, 13)); // NOI18N
        jButtonhome.setForeground(new java.awt.Color(0, 0, 0));
        jButtonhome.setText("HOME");
        jButtonhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Titillium Web", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Course Masterlist");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonhome)
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonhome, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(228, 120, 51));

        jButtonADDCrs.setBackground(new java.awt.Color(242, 241, 239));
        jButtonADDCrs.setFont(new java.awt.Font("Titillium Web", 0, 18)); // NOI18N
        jButtonADDCrs.setForeground(new java.awt.Color(0, 0, 0));
        jButtonADDCrs.setText("ADD");
        jButtonADDCrs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonADDCrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDCrsActionPerformed(evt);
            }
        });

        jButtonEDITCrs.setBackground(new java.awt.Color(242, 241, 239));
        jButtonEDITCrs.setFont(new java.awt.Font("Titillium Web", 0, 18)); // NOI18N
        jButtonEDITCrs.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEDITCrs.setText("EDIT");
        jButtonEDITCrs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEDITCrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEDITCrsActionPerformed(evt);
            }
        });

        jButtonDELETECrs.setBackground(new java.awt.Color(242, 241, 239));
        jButtonDELETECrs.setFont(new java.awt.Font("Titillium Web", 0, 18)); // NOI18N
        jButtonDELETECrs.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDELETECrs.setText("DELETE");
        jButtonDELETECrs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDELETECrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDELETECrsActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Titillium Web", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Titillium Web", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("COLLEGE:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonADDCrs, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEDITCrs, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(jButtonDELETECrs, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, 0, 400, Short.MAX_VALUE)
                .addGap(90, 90, 90))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEDITCrs, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDELETECrs, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonADDCrs, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public void populateTable(String a)
    {
        CourseQuery cq = new CourseQuery();
        ArrayList<Course> cList = cq.courseList(a);       
        
        String[] colNames = {"Course ID", "Course Name", "College Name"};        
        Object[][] rows = new Object[cList.size()][3]; 
        
        for(int i=0; i < cList.size(); i++) // i=
        {
            rows[i][0] = cList.get(i).getCourse_id(); 
            rows[i][1] = cList.get(i).getCourse_name();
            rows[i][2] = cList.get(i).getCollegeName();
        }
        MyModel mmd = new MyModel(rows, colNames);
        jTable1.setModel(mmd);
        jTable1.setRowHeight(50);        
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
    }
    public void refreshJtable() {//c
        jTable1.setModel(new DefaultTableModel());
        populateTable(null);       
    }

    private void jButtonhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhomeActionPerformed
        menuMain home = new menuMain();
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null);
        home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonhomeActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       int selectedindex = jComboBox1.getSelectedIndex();//c
        if(selectedindex==0)
        {
            populateTable(null);
        }else{
            selectedindex--;
            colList.get(selectedindex); 
          // System.out.println(colList.get(selectedindex).getCollege_id());      
           String ID = colList.get(selectedindex).getCollege_id();
            populateTable(ID);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    int rowIndex = jTable1.getSelectedRow();       
    selectedvalue = jTable1.getValueAt(rowIndex, 0).toString(); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonADDCrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDCrsActionPerformed
        ADDCourse courseadd = new ADDCourse();
        courseadd.setVisible(true);
        courseadd.pack();
        courseadd.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonADDCrsActionPerformed

    private void jButtonEDITCrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEDITCrsActionPerformed
        EditCourse.Current_CourseID = selectedvalue;
        if(selectedvalue!=null) {
            EditCourse ec = new EditCourse();
            ec.setVisible(true);
            ec.pack();
            ec.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else {
             JOptionPane.showMessageDialog(null, "Please select a Course to edit\nand Try Again!", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEDITCrsActionPerformed

    private void jButtonDELETECrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDELETECrsActionPerformed
        if(selectedvalue != null) {
            
            int result = JOptionPane.showConfirmDialog(null, "Do you want to delete this course?");
            if (result == JOptionPane.YES_OPTION) {
                CourseQuery cq = new CourseQuery();
                cq.deleteCourse(selectedvalue);
                refreshJtable();
            }  
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a Course to delete\nand Try Again!", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDELETECrsActionPerformed
   public void fillCombo()
    {
        jComboBox1.addItem("All");
        for(int i=0;i < colList.size(); i++)
        {
           
            jComboBox1.addItem(colList.get(i).getCollege_name());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterCollege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterCollege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterCollege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterCollege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterCollege().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADDCrs;
    private javax.swing.JButton jButtonDELETECrs;
    private javax.swing.JButton jButtonEDITCrs;
    private javax.swing.JButton jButtonhome;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
